services:
  postgres:
    build:
      context: .
      args:
        PG_VERSION: 18
        POSTGIS_VERSION: "3.6"
    env_file: ".env"
    environment:
      PG_AUTO_INIT: "1"
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql
#      - ./seed.sql:/docker-entrypoint-initdb.d/20-seed.sql:ro
